---
# Setup all computers with same environment

- name: Setup all computers with same environment
  hosts: all:!ARM-machines
  become: yes
  serial: 1 # only running one host at a time
  any_errors_fatal: true
  max_fail_percentage: 0

  tasks:

    # do "apt-get update", to ensure latest pkg lists
    - name: update the cache
      apt:
        update-cache: yes
        cache_valid_time: 3600
      changed_when: 0

    # install packages
    - name: install packages for personal environment
      apt:
        pkg:
        - mosh
        - cowsay
        - snapd
        - lolcat
        - mtr
        - colormake
        - fail2ban
        - ufw
        - unattended-upgrades
        - logwatch

    # Install snap packages
    - name: install snaps
      community.general.snap:
        name: lsd
        state: present

    - name: setup aliases
      blockinfile:
        path: /home/adam/.bashrc
        state: present
        content: |
            alias ls='lsd'
            alias uptime='uptime | cowsay | lolcat'
            alias home='ssh {{ home_alias }}'
            alias work='ssh {{ work_alias }}'
            alias lolemp='ssh {{ web_alias }}'
            alias plz='sudo !!'
            alias ping='mtr'
            alias nuke='kill -9'
            alias zzz='sudo shutdown now'
            alias rrr='sudo reboot now'
            alias make='colormake'

    # Add and config user
    - name: Change root password
      user: name=root password="{{ UBUNTU_COMMON_ROOT_PASSWORD }}"

    - name: Add user
      user: name={{ ubuntu_common_deploy_user_name }} password="{{ UBUNTU_COMMON_DEPLOY_PASSWORD }}" shell=/bin/bash

    - name: Set authorized keys from URL
      authorized_key:
        user: adam
        state: present
        key: https://github.com/adamgalt.keys

    - name: Add user to sudoers
      lineinfile: dest=/etc/sudoers
                  regexp="{{ ubuntu_common_deploy_user_name }} ALL"
                  line="{{ ubuntu_common_deploy_user_name }} ALL=(ALL) ALL"
                  state=present

    # Security enforcement    

    - name: Setup ufw
      ufw: state=enabled policy=deny

    - name: Allow ssh traffic
      ufw: rule=allow port={{ ubuntu_common_ssh_port }} proto=tcp

    - name: Allow mosh traffic
      ufw: rule=allow proto=udp port={{ ubuntu_common_mosh_from_port }}:{{ ubuntu_common_mosh_to_port }}
    
    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: Restart ssh

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
