---
# Setup all computers with same environment

- name: Setup all computers with same environment
  hosts: all
  become: yes
  serial: 1 # only running one host at a time
  any_errors_fatal: true
  max_fail_percentage: 0

  tasks:

    # do "apt-get update", to ensure latest pkg lists
    - name: update the cache
      apt:
        update-cache: yes
        cache_valid_time: 3600
      changed_when: 0

    # list packages that have updates available
    - name: install packages for personal environment
      apt:
        pkg:
        - mosh
        - cowsay
        - snapd
        - lolcat
        - mtr
        - colormake

    # Install snap packages
    - name: install snaps
      community.general.snap:
        name: lsd
        state: present

    - name: setup aliases
      blockinfile:
        path: /home/adam/.bashrc
        state: present
        content: |
            alias ls='lsd'
            alias uptime='uptime | cowsay | lolcat'
            alias home='ssh adam@home.galt.me'
            alias work='ssh adam@login.robots.ox.ac.uk'
            alias lolemp='ssh adam@galt.me'
            alias plz='sudo !!'
            alias ping='mtr'
            alias nuke='kill -9'
            alias zzz='sudo shutdown now'
            alias rrr='sudo reboot now'
            alias make='colormake'
