---
- name: Shutdown LAN machines
  hosts: zabbix
  become: yes
  gather_facts: no 
  vars:
    ansible_python_interpreter: /usr/bin/python3 


  tasks:
    - name: Shutdown computers
      community.general.shutdown:
